services:
  db:
    container_name: financiera-db-ci
    env_file:
      - .env.ci
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -u root -p$$MYSQL_ROOT_PASSWORD --silent",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 40s
    networks:
      - backend_network

  backend:
    container_name: financiera-api-ci
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.ci
    # Ejecutamos las pruebas y nos salimos
    command: >
      sh -c "pip install pytest httpx pytest-asyncio && pytest tests/ -v"
    networks:
      - backend_network
