services:
  db:
    container_name: ${DB_CONTAINER_NAME:-new-financieras-db-test}
    env_file:
      - .env.test
    restart: unless-stopped
    volumes:
      - mysql_data_test:/var/lib/mysql
    networks:
      - backend_network
      - npm_network
  backend:
    container_name: ${BACKEND_CONTAINER_NAME:-new-financieras-api-test}
    env_file:
      - .env.test
    restart: always
    networks:
      - backend_network
      - npm_network

networks:
  npm_network:
    external: true
    name: ${NPM_EXTERNAL_NETWORK:-npm_network}
volumes:
  mysql_data_test:
    driver: local