services:
  db:
    env_file:
      - .env.local
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

  backend:
    env_file:
      - .env.local
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./app:/app/app
      - ./migrations:/app/migrations
      - ./public:/app/public
    restart: unless-stopped
