services:
  db:
    env_file:
      - .env.test
    ports: []
    volumes: []

  backend:
    env_file:
      - .env.test
    ports: []
    volumes: []
    environment:
      DEBUG: "True"
      DATABASE_HOST: db
