"""add original_filename to master_templates

Revision ID: 1e7a7ee8b295
Revises: 1eab1a7a3ff2
Create Date: 2026-05-06 14:27:30.318813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e7a7ee8b295'
down_revision: Union[str, Sequence[str], None] = '1eab1a7a3ff2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_master_templates', sa.Column('original_filename', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_master_templates', 'original_filename')
    # ### end Alembic commands ###
