"""make user_id nullable for guest users

Revision ID: 1eab1a7a3ff2
Revises: b2c4f7e3d901
Create Date: 2026-04-28 22:58:37.342065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '1eab1a7a3ff2'
down_revision: Union[str, Sequence[str], None] = 'b2c4f7e3d901'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('main_calculations', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('main_calculations', 'user_id',
               existing_type=mysql.BIGINT(unsigned=True),
               nullable=False)
    # ### end Alembic commands ###
