"""17 de marzo

Revision ID: 4f709e805e2a
Revises: f8621f909e0c
Create Date: 2026-03-17 15:06:33.338325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f709e805e2a'
down_revision: Union[str, Sequence[str], None] = 'f8621f909e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_reports', sa.Column('type', sa.Enum('valora', 'kapital', name='reporttype'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_reports', 'type')
    # ### end Alembic commands ###
