"""add_value_to_template_code

Revision ID: 82bfcd1ea404
Revises: 1e7a7ee8b295
Create Date: 2026-05-14 16:16:13.097993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82bfcd1ea404'
down_revision: Union[str, Sequence[str], None] = '1e7a7ee8b295'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_template_codes', sa.Column('value', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_template_codes', 'value')
    # ### end Alembic commands ###
