"""update main

Revision ID: 924419cec6fa
Revises: f08773febd3c
Create Date: 2026-03-13 21:32:29.676029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '924419cec6fa'
down_revision: Union[str, Sequence[str], None] = 'f08773febd3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('main_covers',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.Enum('imagen_adjuntada', 'personalizada', name='covertype'), nullable=False),
    sa.Column('portada_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('primer_imagen_footer_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('segundo_imagen_footer_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portada_id'], ['cms_media.id'], ),
    sa.ForeignKeyConstraint(['primer_imagen_footer_id'], ['cms_media.id'], ),
    sa.ForeignKeyConstraint(['segundo_imagen_footer_id'], ['cms_media.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('main_reports',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('calculation_id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('moneda', sa.String(length=10), nullable=True),
    sa.Column('sector_empresa', sa.String(length=50), nullable=True),
    sa.Column('bono_ajustado', sa.String(length=50), nullable=True),
    sa.Column('link_pago', sa.String(length=555), nullable=True),
    sa.Column('contenido', sa.String(length=255), nullable=True),
    sa.Column('portada_id', mysql.BIGINT(unsigned=True), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['calculation_id'], ['main_calculations.id'], ),
    sa.ForeignKeyConstraint(['portada_id'], ['main_covers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('main_reports')
    op.drop_table('main_covers')
    # ### end Alembic commands ###
