"""add coordinate column to template_codes

Revision ID: ec220c2f8350
Revises: 0f119cab9605
Create Date: 2026-05-29 16:19:24.022899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec220c2f8350'
down_revision: Union[str, Sequence[str], None] = '0f119cab9605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_template_codes', sa.Column('coordinate', sa.String(length=15), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('main_template_codes', 'coordinate')
    # ### end Alembic commands ###
