"""update main_report_cover

Revision ID: f86674b52963
Revises: 924419cec6fa
Create Date: 2026-03-13 21:43:55.692310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'f86674b52963'
down_revision: Union[str, Sequence[str], None] = '924419cec6fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('main_covers', sa.Column('logo_superior_id', mysql.BIGINT(unsigned=True), nullable=True))
    op.add_column('main_covers', sa.Column('imagen_central_id', mysql.BIGINT(unsigned=True), nullable=True))
    op.add_column('main_covers', sa.Column('logo_inferior_id', mysql.BIGINT(unsigned=True), nullable=True))
    op.add_column('main_covers', sa.Column('imagen_fondo_id', mysql.BIGINT(unsigned=True), nullable=True))
    op.create_foreign_key(None, 'main_covers', 'cms_media', ['logo_inferior_id'], ['id'])
    op.create_foreign_key(None, 'main_covers', 'cms_media', ['imagen_fondo_id'], ['id'])
    op.create_foreign_key(None, 'main_covers', 'cms_media', ['logo_superior_id'], ['id'])
    op.create_foreign_key(None, 'main_covers', 'cms_media', ['imagen_central_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'main_covers', type_='foreignkey')
    op.drop_constraint(None, 'main_covers', type_='foreignkey')
    op.drop_constraint(None, 'main_covers', type_='foreignkey')
    op.drop_constraint(None, 'main_covers', type_='foreignkey')
    op.drop_column('main_covers', 'imagen_fondo_id')
    op.drop_column('main_covers', 'logo_inferior_id')
    op.drop_column('main_covers', 'imagen_central_id')
    op.drop_column('main_covers', 'logo_superior_id')
    # ### end Alembic commands ###
